import Image from "next/image";
import Link from "next/link";
import {OrderLauncher} from "./order-modal";

export type Variant="spice"|"joy"|"heritage"|"chatore";
const copy={
 spice:{eyebrow:"Pure vegetarian · Abu Dhabi",title:"Indian street food, made the way it should be.",intro:"Bold flavours, fresh ingredients and the joyful chaos of India—served in the heart of Abu Dhabi.",image:"/food-spice.png",brand:"CHAAT JUNCTION"},
 joy:{eyebrow:"Pure vegetarian · Full of joy",title:"Authentic Indian street food, full of joy.",intro:"Big flavour, bright spices and the street-food classics you love—served fresh in the heart of Abu Dhabi.",image:"/food-joy.png",brand:"Chaat Junction"},
 heritage:{eyebrow:"Serving Abu Dhabi since 2020",title:"Authentic Indian street food, served with heart.",intro:"From crisp pani puri to comforting classics, discover the colours and flavours of India in the heart of Abu Dhabi.",image:"/food-heritage.png",brand:"CJ | Chaat Junction"},
 chatore:{eyebrow:"Pure vegetarian · India on a plate",title:"Where every craving finds its Indian soul.",intro:"A warmer, restaurant-led expression inspired by sister brand Chatore—rich green, festive gold and generous Indian flavours.",image:"/food-chatore.png",brand:"CHAAT JUNCTION"}
};
const dishes=[
 ["Pani Puri","Crisp puris, bright chutneys and a burst of spice.","/dishes/pani-puri.png"],
 ["Papdi Chaat","Cool yogurt, tamarind, mint, sev and pomegranate.","/dishes/papdi-chaat.png"],
 ["Pav Bhaji","Mumbai-style comfort, finished with butter and lime.","/dishes/pav-bhaji.png"],
 ["Dosa","Golden, crisp and served with chutney and sambar.","/dishes/dosa.png"]
];
const reviews=[
 {kind:"Recent",name:"Maria Wafa",rating:"4/5",branch:"Madinat Zayed",when:"5 months ago",text:"Enjoyed the wide chaat selection, comfortable outdoor seating and a piping-hot aloo paratha.",url:"https://www.zomato.com/abudhabi/chaat-junction-1-madinat-zayed/reviews"},
 {kind:"Recent",name:"Riya Thube",rating:"5/5",branch:"Madinat Zayed",when:"6 months ago",text:"Found the pani puri authentically Mumbai-style and highlighted the attentive, friendly service.",url:"https://www.zomato.com/abudhabi/chaat-junction-1-madinat-zayed/reviews"},
 {kind:"Recent",name:"Ratheesh Ravi",rating:"1/5",branch:"Hamdan",when:"5 months ago",text:"Reported a long wait and felt the team did not acknowledge or attend to the table promptly.",url:"https://www.zomato.com/abudhabi/chaat-junction-restaurant-al-markaziya/reviews"},
 {kind:"Guest favourite",name:"Gurpreet Kaur",rating:"5/5",branch:"Madinat Zayed",when:"Oct 2024",text:"Called it a go-to place for pani puri and vada pav, with an especially strong drinks selection.",url:"https://www.zomato.com/abudhabi/chaat-junction-1-madinat-zayed/reviews"},
 {kind:"Guest favourite",name:"Kunaal Kucheria",rating:"5/5",branch:"Hamdan",when:"Jul 2023",text:"Praised the consistently good menu and described the pav bhaji as exceptional.",url:"https://www.zomato.com/abudhabi/chaat-junction-restaurant-al-markaziya/reviews"},
 {kind:"Guest favourite",name:"Hisha Dsouza",rating:"5/5",branch:"Hamdan",when:"Apr 2024",text:"Highlighted the food, shakes and welcoming service during the visit.",url:"https://www.zomato.com/abudhabi/chaat-junction-restaurant-al-markaziya/reviews"}
];

export function ConceptHome({variant}:{variant:Variant}){
 const c=copy[variant];
 const base=variant==="spice"?"":`/${variant}`;
 return <main id="top" className={`site ${variant}`}>
  {variant==="heritage"&&<div className="topbar"><span>◇ Pure vegetarian</span><span>✦ Serving Abu Dhabi since 2020</span><span>♡</span></div>}
  <header><a className="logo" href="#top"><BrandMark/></a><nav><Link href={`${base}/menu`}>Menu</Link><a href="#story">Our story</a><a href="#locations">Locations</a><a href="#catering">Catering</a></nav><OrderLauncher className="order"/><MobileNav base={base}/></header>
  <section className="hero">
   <div className="heroCopy"><p className="eyebrow">{c.eyebrow}</p>{variant!=="heritage"&&<p className="displayBrand">{c.brand}<small>Abu Dhabi</small></p>}<h1>{c.title}</h1><p className="intro">{c.intro}</p><div className="actions"><Link className="primary" href={`${base}/menu`}>View menu</Link><OrderLauncher className="secondary"/></div><div className="proof"><span>⌂ Hamdan Street</span><span>⌖ Madinat Zayed</span></div></div>
   <div className="heroImage"><Image src={c.image} alt="Colourful Indian chaat and street food" fill priority sizes="(max-width:900px) 100vw, 58vw"/><em>Serving Abu Dhabi<br/>since 2020</em></div>
  </section>
  <div className="ticker" aria-label="Freshly prepared · Indian street favourites · Two Abu Dhabi locations · Pure vegetarian"><div className="tickerTrack"><span>Freshly prepared</span><i>✦</i><span>Indian street favourites</span><i>✦</i><span>Two Abu Dhabi locations</span><i>✦</i><span>Pure vegetarian</span><i>✦</i></div><div className="tickerTrack" aria-hidden="true"><span>Freshly prepared</span><i>✦</i><span>Indian street favourites</span><i>✦</i><span>Two Abu Dhabi locations</span><i>✦</i><span>Pure vegetarian</span><i>✦</i></div></div>
  <section id="menu" className="shell menu"><Heading kicker="Crowd favourites" title="Start with something chaatpata." text="Tangy, crunchy, spicy and sweet—familiar Indian street-food favourites prepared fresh for every order."/><div className="dishGrid">{dishes.map((d,i)=><article className="dish" key={d[0]}><span>0{i+1}</span><div className="dishArt"><Image src={d[2]} alt={d[0]} fill sizes="(max-width:700px) 100vw, 25vw"/></div><h3>{d[0]}</h3><p>{d[1]}</p><Link href={`${base}/menu`}>See on menu ↗</Link></article>)}</div><Link className="more" href={`${base}/menu`}>Explore the full menu →</Link></section>
  <section id="story" className="story"><div className="storyCopy"><p className="kicker">About us</p><h2>Small beginning.<br/>Big flavour.</h2><p>Chaat Junction was born in Abu Dhabi in 2020, during a challenging year, with one clear purpose: bring the irresistible flavours of Indian street food to the city with care for taste, presentation and quality.</p><p>The warm response led to a second location in 2022. In 2024, the journey grew again with sister brand <a className="storyLink" href="https://chatorerestaurant.com/" target="_blank" rel="noreferrer">Chatore Restaurant ↗</a>—another expression of the food and hospitality guests had come to love.</p></div><div className="journey" aria-label="Chaat Junction journey from 2020 to 2024"><div className="route"><i/><i/><i/></div><article className="milestone m2020"><span className="flag"/><b>Step 01</b><strong>2020</strong><p>The first Chaat Junction opens in Abu Dhabi</p></article><article className="milestone m2022"><span className="flag"/><b>Step 02</b><strong>2022</strong><p>A second location welcomes more chaat lovers</p></article><article className="milestone m2024"><span className="flag"/><b>Step 03</b><strong>2024</strong><p>Sister brand Chatore joins the journey</p></article><div className="journeyTitle"><span>Our flavour trail</span><strong>Milestones</strong></div></div></section>
  <section id="locations" className="shell locations"><Heading kicker="Come hungry" title="Two stops for your chaat fix." text="Eat in, take away or order your favourites to your door."/><div className="locationGrid"><Location n="01" area="Al Danah" title="Hamdan Street" phone="+971 2 675 2072" tel="+97126752072" maps="https://www.google.com/maps/search/?api=1&query=Chaat+Junction+Hamdan+Street+Abu+Dhabi" note="Hamdan Bin Mohammed Street, central Abu Dhabi."/><Location n="02" area="Madinat Zayed" title="Madinat Zayed" phone="+971 2 441 1916" tel="+97124411916" maps="https://www.google.com/maps/search/?api=1&query=Chaat+Junction+Madinat+Zayed+Abu+Dhabi" note="Opposite Madinat Zayed Fish Market, near Shoe Mart."/></div></section>
  <section className="shell reviews"><Heading kicker="What guests are saying" title="Chaat worth talking about." text="A balanced snapshot of recent public feedback and recurring favourites from both Abu Dhabi branches."/><div className="reviewGrid">{reviews.map(review=><article key={`${review.name}-${review.when}`}><div><span>{review.kind}</span><b>{review.rating}</b></div><p>“{review.text}”</p><footer><strong>{review.name}</strong><small>{review.branch} · {review.when}</small></footer><a href={review.url} target="_blank" rel="noreferrer">Read on Zomato ↗</a></article>)}</div><p className="reviewStamp">Public review snapshot checked August 2026. Ratings and review order may change on the source platform.</p></section>
  <section id="catering" className="shell catering"><div><p className="kicker">Chaat for the whole crowd</p><h2>Bring the junction to your celebration.</h2></div><p>Planning an office gathering, birthday or community event? Tell us what you have in mind and let the team shape a menu.</p><a className="primary" href="mailto:chaatjunctionabudhabi@gmail.com">Ask about catering</a></section>
  <section id="order" className="cta"><p className="kicker">Craving something?</p><h2>Chaat is a good idea.</h2><p>Choose your branch and preferred delivery app.</p><div className="actions"><OrderLauncher className="primary" label="Choose delivery app"/></div></section>
  <div className="mobileQuick"><Link href={`${base}/menu`}>Menu</Link><a href="#locations">Locations</a><OrderLauncher label="Order"/></div>
  <footer><a className="logo" href="#top"><BrandMark/></a><p>Pure vegetarian Indian street food in Abu Dhabi, serving Hamdan Street and Madinat Zayed.<br/><span className="conceptCredit">Independent website concept by Quirkly.life</span></p><div><a href="#menu">Menu</a><a href="#story">Story</a><a href="#locations">Locations</a><a href="https://chatorerestaurant.com/" target="_blank" rel="noreferrer">Other Brands: Chatore ↗</a><a href="#top">Back to top ↑</a></div></footer>
 </main>
}
function Heading({kicker,title,text}:{kicker:string,title:string,text:string}){return <div className="heading"><div><p className="kicker">{kicker}</p><h2>{title}</h2></div><p>{text}</p></div>}
function BrandMark(){return <span className="brandMark"><i><b>C</b><b>J</b></i><span><span className="brandName"><strong>Chaat Junction</strong><span className="vegMark" role="img" aria-label="Pure vegetarian"><span/></span></span><small>Abu Dhabi</small></span></span>}
function MobileNav({base}:{base:string}){return <details className="mobileNav"><summary aria-label="Open navigation">☰</summary><div><Link href={`${base}/menu`}>Menu</Link><a href="#story">Our story</a><a href="#locations">Locations</a><a href="#catering">Catering</a></div></details>}
function Location({n,area,title,phone,tel,maps,note}:{n:string,area:string,title:string,phone:string,tel:string,maps:string,note:string}){return <article><span>{n}</span><small>{area}</small><h3>{title}</h3><p>{note}</p><a href={`tel:${tel}`}>{phone}</a><a href={maps} target="_blank" rel="noreferrer">Get directions ↗</a></article>}
